# This is a basic workflow to help you get started with Actions

name: msm-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
 workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Zip installer Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm8150
          - mh2lm
          - nabu
          - cepheus
          - vayu-huaxing
          - vayu-tianma
          # sm8550
          - fuxi


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
      - name: Install required packages
        run: |
          # Purge any existing or leftover references to the broken PPA
          sudo rm -f /etc/apt/sources.list.d/*sdl2-backport*.list
          sudo rm -f /etc/apt/sources.list.d/*cybermax-dexter*.list
          
          # Configure multiarch and install native packages
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext libgcc-s1:i386 libstdc++6:i386 libsdl2-dev
          sudo apt-get -y install wine wine32 wine64

      - name: Build device ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }} --installer-zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with: # Artifact name
          name: ${{ matrix.device }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.zip
